### ISSUE TITLE
Resultat test application parametre biomedical-Web 

### ISSUE THREAD

**Issue by uwajambo** [biomedical-inc/Release-1#12]
Bonjour Gilles 
Voici les bogues trouvés lors du test repris en marge

TicketID:   TickLogin
Élément du bogue: Login
Priorité bogue: 1
Version release: Release1

Description: 
1. L'utilisateur est capable d'entrer dans le système avec un mot de passe erroné
2. Un utilisateur rentre le mot de passe erroné, le système renvoie un pop up affichant ses identifiants en caractères visibles. 
3.Le système devait générer plutôt un message demandant demandant de saisir les identifiants valables.
4.  La page n'a pas de boutons qui permet un nouvel utilisateur de créer un compte.

Merci 
Jean

**Comment by gilles-hector** [comment]
Bonjour Jean 
Billet assigné  a Mawran
billet résolu .

**Comment by uwajambo** [comment]
Bonjour Gilles

Le billet est maintenant fermé avec succes

Jean Bosco
