### ISSUE TITLE
Resultat Test Systeme Embarqué parametres biomedicaaux

### ISSUE THREAD

**Issue by uwajambo** [biomedical-inc/Release-1#19]
Ticket: ShellMesure
Priorite: 1
Module testé : Système embarqué

Description du bogue :
Le système n’affiche pas le message de bienvenue <<Welcome>> au lancement.

Jean Bosco
1 Avril 2019

**Comment by gilles-hector** [comment]
problème corrigé par  Kilo

**Comment by uwajambo** [comment]
Le billet est maintenant fermé avec succes
